### ISSUE TITLE
Cycle matrix

### ISSUE THREAD

**Issue by westdun** [nilsnolde/OSMtools#64]
Hello Nils,

Love OSM tools it got me out of a spot of bother recently. 

I'm having a small problem now though trying to create a matrix for cycling or walking ODs. The error I receive is 
" 400 (Parameter 'sources/destinations=100' is out of range. Maximum possible value is 25.)"

No such problems using the same ODs for driving.

Any solutions?

many thanks
D

**Comment by nilsnolde** [comment]
Yep, that's a rate limit thing, see here:
https://openrouteservice.org/ratelimits/

It was due to the fact, that those profiles were not using any speedup algorithm until very recently. However, that's fixed by now. I'll let the devs know to increase the number of possible input:
https://github.com/GIScience/openrouteservice/issues/225
